#!/usr/bin/env node

/**
 * DESCRIPTION
 * parse `snyk test --json` out, rolling up vulnerabilities by CVE/GHSA, grouped by severity
 *
 * USAGE
 * ./snyk-parse path/to/snyk_test_output.json
 *
 */

import { readFileSync } from 'node:fs';

const vulns = {
  'critical': {},
  'high': {},
  'medium': {},
  'low': {},
  'ignore': {},
};


//
// collect input
//
let json;
if (process.argv[2]) {
  json = JSON.parse(readFileSync(process.argv[2]));
} else {
  console.error("no input file specified");
  process.exit(1);
}

// show all affected packages? default: false
const verbose = process.argv.some(av => av === '-v' || av === '--verbose')

if (!Array.isArray(json.vulnerabilities)) {
  console.error(`sorry; could not process ${process.argv[2]}`);
  if (json && json.error) {
    console.error(json.error);
  } else {
    console.error("Output was not an array.");
  }
  process.exit(1);
}

//
// parse input
//
json.vulnerabilities.forEach(i => {
  let entry = null;

  // collect vulerabilities with CVE/GHSA identifiers, grouped by severity
  let id = i.identifiers?.CVE?.[0] || i.identifiers?.GHSA?.[0];
  if (id) {
    if (!vulns[i.severityWithCritical][id]) {
      vulns[i.severityWithCritical][id] = {
        moduleName: i.moduleName,
        fixedIn: i.fixedIn,
        title: i.title,
        from: [],
        version: [],
      };
    }

    entry = vulns[i.severityWithCritical][id];
  }
  // collect so-called vulnerabilities without identifiers
  // under the fake-severity "ignore"
  else {
    id = i.id;
    if (!vulns['ignore'][id]) {
      vulns['ignore'][id] = {
        moduleName: i.moduleName,
        fixedIn: i.fixedIn,
        title: i.title,
        from: [],
        version: [],
      };
    }

    entry = vulns['ignore'][id];
  }

  // drop the current package, because of course the current package is vulnerable
  entry.from.push(i.from.slice(1).join(" < "));

  // keep a list of vulnerable versions
  entry.version = Array.from(new Set([...entry.version, i.version]));
});


//
// output formatter
//
const fromFormat = (list) => {
  // show all paths
  if (verbose) {
    return list.map(i => `\n\t${i}`).toSorted((a, b) => a.localeCompare(b));
  }

  // show 1 path and a count of vulnerable paths
  return `\n\t${list[0]} and ${list.length - 1} others`;
};

//
// display output
//
Object.entries(vulns).forEach(([severity, vList]) => {
  if (Object.entries(vList).length) {
    Object.entries(vList).forEach(([cve, i]) => {
      console.log(`${cve}\t${severity.toUpperCase()}\t${i.moduleName}\t${i.version}\t${i.fixedIn}\t${i.title}${fromFormat(i.from)}`);
    })
  }
});
